export enum Update {
    SelectedBackground = 'updateSelectedBackground',
    AuthorizationState = 'updateAuthorizationState',
    ConnectionState = 'updateConnectionState',
    Option = 'updateOption',
    NewMessage = 'updateNewMessage',
    UserStatus = 'updateUserStatus',
    ScopeNotificationSettings = 'updateScopeNotificationSettings',
    HavePendingNotifications = 'updateHavePendingNotifications',
    ChatReadOutbox = 'updateChatReadOutbox',
    ChatReadInbox = 'updateChatReadInbox',
    User = 'updateUser',
    NewChat = 'updateNewChat',
    ChatNotificationSettings = 'updateChatNotificationSettings',
    ChatLastMessage = 'updateChatLastMessage',
    ChatOrder = 'updateChatOrder',
    UserFullInfo = 'updateUserFullInfo',
    Ok = 'ok',
    Supergroup = 'updateSupergroup',
    BasicGroup = 'updateBasicGroup'
}
